# claude-lane configuration file
# Place this file at ~/.claude/config.yaml

# Define your API endpoints here
# Each profile needs a base_url (key_ref is now optional and defaults to profile name)
endpoints:
  # Official Anthropic API (requires API key)
  official-api:
    base_url: "https://api.anthropic.com"
  
  # Example proxy/relay service
  proxy:
    base_url: "https://your-proxy.example.com/v1"

  # Example alternative service (like Kimi)
  kimi:
    base_url: "https://api.moonshot.cn/anthropic"
  
  qwen:
    base_url: "https://dashscope-intl.aliyuncs.com/api/v2/apps/claude-code-proxy"

  glm:
    base_url: "https://open.bigmodel.cn/api/anthropic"

  # Local development server
  local:
    base_url: "http://localhost:8080/v1"

# Usage (v1.2.0+):
# Default behavior (no config needed):
#    claude-lane "Hello, how are you?"        # Uses Claude Code's built-in web login
#    claude-lane                              # Interactive mode with web login
#
# API key mode (requires config):
# 1. Store your API keys securely:
#    claude-lane set-key official-api sk-ant-api03-...
#    claude-lane set-key proxy your-proxy-key
#    claude-lane set-key kimi your-kimi-key
#
# 2. Use API profiles:
#    claude-lane official-api "Write a poem"  # Use official API with key
#    claude-lane proxy "Translate this"       # Use proxy service
#
# 3. Environment-only mode:
#    claude-lane --env-only official-api      # Set env vars only
#
# 4. Check status:
#    claude-lane status                       # Show current configuration